### ISSUE TITLE
Добавить документацию к функции

### ISSUE THREAD

**Issue by Temmmmmo** [profcomff/auth-api#165]
### Основная проблема
В файле с ручками, которые относятся к User(путь: `auth_backend/routes/user.py`), все методы никак не задокументированы.

### Задача
Необходимо разобраться в работе методов и задокументировать их.

P.S. Примеры документации функции можно посмотреть, например, здесь `auth_backend/models/db.py`.

**Comment by 89605502155** [comment]
Привет!
Появилось время и я дописал документацию к методам пользователя.
Ветка называется backend_doc_ferubko.
Мне удалось сделать тебя рецензентом ветки?
С Уважением, Андрей.

**Comment by grigoriev-semyon** [comment]
@89605502155 какой статус?
