### ISSUE TITLE
Задержка повторной отправки письма

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/auth-api#23]

**Comment by dyakovri** [comment]
Точно ишью не фронтовое? Есть ли обязательная задержка между отправками на бэке или можно спамить письмами?

**Comment by grigoriev-semyon** [comment]
@dyakovri задержки нет, отправлять письма можно сколько угодно дергая ручку регистрации

**Comment by dyakovri** [comment]
Ну вот кажется, что на бэке можно это поправить 
Сделать обязательную задержку в минуту
