### ISSUE TITLE
Кнопка забыли пароль+изменение параметров email плагина

### ISSUE THREAD

**Issue by dyakovri** [profcomff/auth-api#4]
From [Сервис авторизации#13](https://github.com/profcomff/.github/issues/13)

**Comment by grigoriev-semyon** [comment]
При изменении мыла приходит новое письмо с проверкой мыла

**Comment by grigoriev-semyon** [comment]
На изменения пароля тоже надо сделать подтверждение через почту

**Comment by grigoriev-semyon** [comment]
@dyakovri

**Comment by dyakovri** [comment]
На любое изменение пароля? На кнопку забыли пароль да, на изменение в личном кабинете можно сделать просто уведомление

**Comment by grigoriev-semyon** [comment]
Изменение по токену -> без уведомлениия

**Comment by grigoriev-semyon** [comment]
Без токена с уведомлением

**Comment by dyakovri** [comment]
А при изменении пароля, если человек залогинен, будем у него пароль спрашивать еще раз?)

**Comment by grigoriev-semyon** [comment]
думаю да

**Comment by grigoriev-semyon** [comment]
Тесты пишу под такую логику 
1) При смене мыла логин идет под старым мылом до момента подтверждения нового. Токены остаются действительными.
2) Приходит ссылка на подтверждение мыла и только после подтверждения в БД делается замена и логин будет по новому мылу.

**Comment by grigoriev-semyon** [comment]
Ручки в тестах расположил по адресам
Изменение пароля
/email/reset/password/{user_id}/request
/email/reset/password/{user_id}/

Мыла
/email/reset/email/{user_id}/request
/email/reset/email/{user_id}/
