### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by dyakovri** [profcomff/auth-api#64]
- [x] Как подготовиться к локальной разработке
- [x] Как запустить контейнер локально
- [x] Как пользоваться CLI (просто и из докера)
- [x] Как сделать, чтоб методы аутентификации не 500тили (ака как каждому методу передать ключи и где их взять)
- [x] Где взять готовые либы аутентификации

**Comment by dyakovri** [comment]
Возможно, стоит начать писать про аутх на вики, а тут оставить краткое содержание и ссылки

**Comment by grigoriev-semyon** [comment]
https://github.com/profcomff/.github/wiki/Сервис-авторизации
